version: '3'

services:
  banco:
    image: henriquercxs/banco_citylivinglab:v1
    container_name: testebanco
    networks:
      - minha_rede
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ucs
  indicadores:
    image: henriquercxs/indicadores_citylivinglab:v1
    container_name: indicadores_cliente_d
    networks:
      - minha_rede
    ports:
      - "4200:4200"
      - "5000:5000"
    depends_on:
      - banco
    volumes:
      - c:/TCC:/app/dados
    environment:
      - TZ=America/Sao_Paulo
  coleta:
    image: henriquercxs/coleta_citylivinglab:v1
    container_name: testecoleta
    networks:
      - minha_rede
    ports:
      - "5001:5001"
      - "5002:5002"
    depends_on:
      - banco
    volumes:
      - c:/TCC:/app/dados
    environment:
      - TZ=America/Sao_Paulo    
  nginx:
    image: henriquercxs/proxy_citylivinglab:v1
    container_name: meu_nginx
    networks:
      - minha_rede
    ports:
      - "80:80"
    depends_on:
      - banco
      - coleta
      - indicadores

networks:
  minha_rede:
    driver: bridge